stages:
  - verify
  - test-unit

checkstyle:
  stage: verify
  image: gradle:7-jdk17-jammy
  script:
    - cd server
    - apt update
    - apt -y install checkstyle
    - checkstyle src/ -c ./google_checks.xml

junit:
  stage: test-unit
  image: gradle:7-jdk17-jammy
  script:
    - cd server
    - chmod +x ./gradlew
    - ./gradlew test
