stages:
  - verify
  - build
  - test

cache:
  - key: npm-cache
    paths:
      - client/node_modules
  - key: gradle-cache
    paths:
      - server/.gradle/caches
      - server/.gradle/notifications
      - server/.gradle/wrapper

# verify stage
eslint:
  stage: verify
  image: node:18
  script:
    - cd client
    - npm install
    - npm run eslint

# build stage
build-npm:
  stage: build
  image: node:18.12.1-alpine
  script:
    - cd client
    - npm install webpack-cli -g
    - npm install
    - npm rebuild node-sass
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - client/build/

build-server:
  stage: build
  image: eclipse-temurin:17-jdk-jammy
  script:
    - cd server
    - chmod +x ./gradlew
    - ./gradlew --gradle-user-home .gradle/ build -x test
  artifacts:
    expire_in: 1 week
    paths:
      - server/build/libs/

# test stage
test-server:
  stage: test
  needs:
    - build-server
  image: eclipse-temurin:17-jdk-jammy
  variables:
    MYSQL_DATABASE: test_database
    MYSQL_HOST: localhost
    MYSQL_PORT: 3000
    MYSQL_USER: test_user
    MYSQL_PASSWORD: test_password
  script:
    - cd server
    - chmod +x ./gradlew
    - ./gradlew --gradle-user-home .gradle/ test
  dependencies:
    - build-server
  artifacts:
    when: always
    reports:
      junit:
        - server/build/test-results/test/**/TEST-*.xml
