server:
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: handy-server
  config:
    import: file:./config/handy_server.yml
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    flyway:
      locations: classpath:/db/migration
    hibernate:
      ddl-auto: update
  mail:
    host: ${MAIL_HOST}
    PORT: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
