application:
  config:
    domain: ${HANDY_DOMAIN}
    cors:
      allowed-origins:
        - https://${HANDY_DOMAIN}
        - http://${HANDY_DOMAIN}:3000
        - http://${HANDY_DOMAIN}:4200
    jwt:
      access-token-expiration-time: 60
      refresh-token-expiration-time: 30
      secret: ${HANDY_JWT_SECRET}
    verification:
      token-expiration-time: 24
      email: ${HANDY_VERIFICATION_EMAIL}
